dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceName | lower}}.go"
log-level: warn
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  # Add external interfaces to mock here. Example:
  # github.com/asphaltbuffet/gocard/internal/logging:
  #   interfaces:
  #     Logger: {}
