// Code generated by "stringer -type=Accent -trimprefix="; DO NOT EDIT.

package gocard

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccentNone-0]
	_ = x[AccentRed-1]
	_ = x[AccentBlack-2]
	_ = x[AccentMuted-3]
}

const _Accent_name = "AccentNoneAccentRedAccentBlackAccentMuted"

var _Accent_index = [...]uint8{0, 10, 19, 30, 41}

func (i Accent) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Accent_index)-1 {
		return "Accent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Accent_name[_Accent_index[idx]:_Accent_index[idx+1]]
}
