// Code generated by "stringer -type=BorderStyle -trimprefix="; DO NOT EDIT.

package gocard

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BorderNone-0]
	_ = x[BorderPlain-1]
	_ = x[BorderRounded-2]
	_ = x[BorderDouble-3]
	_ = x[BorderThick-4]
}

const _BorderStyle_name = "BorderNoneBorderPlainBorderRoundedBorderDoubleBorderThick"

var _BorderStyle_index = [...]uint8{0, 10, 21, 34, 46, 57}

func (i BorderStyle) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BorderStyle_index)-1 {
		return "BorderStyle(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BorderStyle_name[_BorderStyle_index[idx]:_BorderStyle_index[idx+1]]
}
