// Code generated by "stringer -type=Rank -trimprefix="; DO NOT EDIT.

package gocard

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoRank-0]
	_ = x[Ace-1]
	_ = x[Two-2]
	_ = x[Three-3]
	_ = x[Four-4]
	_ = x[Five-5]
	_ = x[Six-6]
	_ = x[Seven-7]
	_ = x[Eight-8]
	_ = x[Nine-9]
	_ = x[Ten-10]
	_ = x[Jack-11]
	_ = x[Queen-12]
	_ = x[King-13]
	_ = x[Joker-14]
}

const _Rank_name = "NoRankAceTwoThreeFourFiveSixSevenEightNineTenJackQueenKingJoker"

var _Rank_index = [...]uint8{0, 6, 9, 12, 17, 21, 25, 28, 33, 38, 42, 45, 49, 54, 58, 63}

func (i Rank) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Rank_index)-1 {
		return "Rank(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Rank_name[_Rank_index[idx]:_Rank_index[idx+1]]
}
