// Code generated by "stringer -type=Suit -trimprefix="; DO NOT EDIT.

package gocard

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoSuit-0]
	_ = x[Clubs-1]
	_ = x[Diamonds-2]
	_ = x[Hearts-3]
	_ = x[Spades-4]
}

const _Suit_name = "NoSuitClubsDiamondsHeartsSpades"

var _Suit_index = [...]uint8{0, 6, 11, 19, 25, 31}

func (i Suit) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Suit_index)-1 {
		return "Suit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Suit_name[_Suit_index[idx]:_Suit_index[idx+1]]
}
